# coslatte's starship template

# LEGO THEME
format = """
[â–Ÿ](fg:red)\
$os\
$username\
$memory_usage\
[â–›](fg:red bg:gold)\

[â–Ÿ](fg:gold bg:red)\
$directory\
[â–›](fg:gold bg:green)\

[â–Ÿ](fg:green bg:gold)\
$git_branch\
$git_status\
$git_metrics\
[â–›](fg:green bg:violet)\

[â–Ÿ](fg:violet bg:green)\
$package\
$c\
$rust\
$nodejs\
$java\
$python\
$lua\
[â–›](fg:violet bg:paper)\

[â–Ÿ](fg:paper bg:violet)\
$time\

[â–›](fg:paper)\
$cmd_duration\
$line_break\
$character"""

palette = 'palette1'

[palettes.palette1]
text = "#ccccb5"
crust = "#151a21"
base = "#1b2028"

red = "#e74c3c"
red_deep = "#ec8b14ff"
blue = "#23a9d5"
green = "#6dd393"
gold = "#f39c12"
amber = "#f1c40f"
violet = "#9241f0"
lavender = "#46d4aa"
paper = "#eddba9"

#############
# [MODULES] #
#############
[os]
disabled = false
style = "bg:red fg:crust"
format = '[ $symbol ]($style)'

[os.symbols]
Windows = "ó°²"
Linux = "ó°Œ½"

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[$user ]($style)'

[directory]
style = "bg:gold fg:crust"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = true
truncation_symbol = "â¸« "

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€¾ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "

[localip]
disabled = true
ssh_only = false
format = '[ ğ‹ƒ $localipv4 ]($style)'
style = "bg:gold fg:crust"

[memory_usage]
disabled = false
threshold = 20
symbol = 'ó°›'
style = 'bg:red fg:crust bold'
format = "[[$symbol ram $ram_pct ](fg:crust bg:red)]($style)"

[git_branch]
disabled = false
symbol = "ï˜"
style = "bg:amber"
format = '[[ $symbol $branch ](fg:crust bg:green)]($style)'

[git_status]
disabled = false
style = "bg:amber"
format = '[[($all_status $ahead_behind)](fg:crust bg:green)]($style)'

[git_metrics]
disabled = true
added_style = 'bg:green fg:crust'
deleted_style = 'bg:green fg:gold'
format = '[+$added]($added_style)/[-$deleted]($deleted_style)'

[package]
disabled = false
symbol = "ğŸ— "
style = "208 bold"
format = '[ $symbol $version ]($style)'

##########################
# [PROGRAMING LANGUAGES] #
##########################
[nodejs]
symbol = "îœ˜"
style = "bg:violet"
format = '[[ $symbol($version) ](fg:crust bg:violet)]($style)'

[c]
symbol = "î˜"
style = "bg:violet"
format = '[[ $symbol ($version) ](fg:crust bg:violet)]($style)'

[java]
symbol = "î‰–"
style = "bg:violet"
format = '[[ $symbol (Java v$version) ](fg:crust bg:violet)]($style)'

[rust]
symbol = "î¨"
style = "bg:violet"
format = '[[ $symbol ($version) ](fg:crust bg:violet)]($style)'

[python]
symbol = "î˜†"
style = "bg:violet"
format = '[[ $symbol ($version) (\($virtualenv\)) ](fg:crust bg:violet)]($style)'

[lua]
symbol = "î˜ "
style = "bg:violet"
format = '[[ $symbol ($version) ](fg:crust bg:violet)]($style)'

##########
# [TIME] #
##########
[time]
disabled = false
use_12hr = true
utc_time_offset = "local"
time_format = "%I:%M %p"
style = "bg:lavender"
format = '[[ t = $time ](fg:crust bg:paper)]($style)'

######################
# [COMMAND DURATION] #
######################
[cmd_duration]
show_milliseconds = true
format = " â¯Œ in $duration"
style = "fg:crust"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[line_break]
disabled = false

###############
# [CHARACTER] #
###############
[character]
disabled = false
success_symbol = '[âœ](fg:blue)'
error_symbol = '[âœ—](fg:red)'
vimcmd_symbol = '[âŸ€](fg:violet)'
vimcmd_replace_one_symbol = '[âŸ€](italic fg:lavender)'
vimcmd_replace_symbol = '[âŸ€](italic fg:lavender)'
vimcmd_visual_symbol = '[âŸ€](italic fg:amber)'

